# Generated by Django 6.0.2 on 2026-03-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('tops', 'Верх'), ('bottoms', 'Низ'), ('shoes', 'Обувь'), ('accessories', 'Аксессуары')], max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Мужское'), ('F', 'Женское'), ('U', 'Унисекс')], default='U', max_length=1)),
                ('image_path', models.CharField(max_length=500)),
                ('image_url', models.URLField(blank=True)),
                ('color_name', models.CharField(blank=True, max_length=50)),
                ('color_rgb', models.JSONField(default=list)),
                ('store', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('product_url', models.URLField(blank=True)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'gender'], name='recommendat_categor_37c2cf_idx'), models.Index(fields=['store', 'category'], name='recommendat_store_a748f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('chat_id', models.CharField(max_length=100)),
                ('query_image', models.ImageField(upload_to='queries/%Y/%m/')),
                ('detected_category', models.CharField(choices=[('tops', 'Верх'), ('bottoms', 'Низ'), ('shoes', 'Обувь'), ('accessories', 'Аксессуары')], max_length=20)),
                ('detected_gender', models.CharField(choices=[('M', 'Мужское'), ('F', 'Женское'), ('U', 'Унисекс')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendations', models.ManyToManyField(related_name='queries', to='recommendations.clothingitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
