# Generated by Django 6.0.2 on 2026-04-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothingitem',
            options={'verbose_name': 'Предмет одежды', 'verbose_name_plural': 'Предметы одежды'},
        ),
        migrations.AlterModelOptions(
            name='userquery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос пользователя', 'verbose_name_plural': 'Запросы пользователей'},
        ),
        migrations.RemoveIndex(
            model_name='clothingitem',
            name='recommendat_categor_37c2cf_idx',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='style_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Стиль'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('tops', 'Верхняя одежда'), ('bottoms', 'Брюки и шорты'), ('shoes', 'Обувь'), ('accessories', 'Аксессуары')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='color_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цвет (название)'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='color_rgb',
            field=models.JSONField(blank=True, default=list, help_text='Список [R, G, B]'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='currency',
            field=models.CharField(default='BYN', max_length=10, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='embedding',
            field=models.BinaryField(blank=True, null=True, verbose_name='Вектор CLIP'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужское'), ('F', 'Женское'), ('U', 'Унисекс')], default='U', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='id',
            field=models.CharField(help_text='ID из магазина (напр. lamoda_123)', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='image_path',
            field=models.CharField(max_length=500, verbose_name='Путь к локальному файлу'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='product_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Ссылка на товар'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='store',
            field=models.CharField(blank=True, max_length=100, verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='chat_id',
            field=models.CharField(max_length=100, verbose_name='ID чата'),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='detected_category',
            field=models.CharField(blank=True, choices=[('tops', 'Верхняя одежда'), ('bottoms', 'Брюки и шорты'), ('shoes', 'Обувь'), ('accessories', 'Аксессуары')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='detected_gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужское'), ('F', 'Женское'), ('U', 'Унисекс')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='query_image',
            field=models.ImageField(upload_to='queries/%Y/%m/', verbose_name='Запрос (фото)'),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='recommendations',
            field=models.ManyToManyField(related_name='queries', to='recommendations.clothingitem', verbose_name='Результаты'),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='user_id',
            field=models.CharField(max_length=100, verbose_name='ID пользователя'),
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['category', 'gender', 'is_active'], name='recommendat_categor_87fd83_idx'),
        ),
    ]
