# Generated by Django 6.0.2 on 2026-04-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_clothingitem_options_alter_userquery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
