# Generated by Django 6.0.2 on 2026-04-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_clothingitem_external_id_alter_clothingitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='color_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='color_rgb',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='external_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
